name: UnrealPipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0' # Every Sunday at 4:00 UTC [TODO]

jobs:
  build-and-test:
    runs-on: [self-hosted, windows]
    
    steps:
      # Checkout with LFS
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      # Install Dependencies
      - name: Setup Unreal Engine
        run: |
          echo "Set up self-hosted runner"

      # Workspace Prep & Clean
      - name: Clean previous build outputs
        run: |
          if exist Binaries rmdir /s /q Binaries
          if exist Intermediate rmdir /s /q Intermediate
          if exist Saved rmdir /s /q Saved
      
      # Run BuildGraph [TODO]
      - name: Run BuildGraph UnrealPipeline
        run: |
          echo "run: RunUAT.bat BuildGraph -target=X -script=X.xml"
      
      # Upload Artifacts [TODO]
      - name: Upload Build Artifacts
        run: echo "Upload stuff"