name: UnrealPipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build_configuration:
        description: 'Build Configuration'
        required: true
        default: 'Development'
        type: choice
        options: [Development, Shipping, Debug, Test]
      target_platform:
        description: 'Target Platform'
        required: true
        default: 'Win64'
        type: choice
        options: [Win64, Linux]
      enable_tests:
        description: 'Run Tests'
        required: true
        default: true
        type: boolean
      enable_packaging:
        description: 'Package Build'
        required: true
        default: true
        type: boolean
      build_script_path:
        description: 'Override path to Build.xml (optional)'
        required: false
        default: ''
        type: string

env:
  PROJECT_NAME: FPSProject
  UE_VERSION: "5.5"
  UE_ENGINE_PATH: "F:\\UE5.5-Installed"
  BUILD_CONFIGURATION: ${{ github.event.inputs.build_configuration || 'Development' }}
  TARGET_PLATFORM: ${{ github.event.inputs.target_platform || 'Win64' }}

jobs:
  build-and-test:
    name: Build, Cook, Package & Test
    runs-on: [self-hosted, windows]
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Verify Precompiled Engine
        shell: powershell
        run: |
          $UEPath = $env:UE_ENGINE_PATH
          if (!(Test-Path "$UEPath\Engine\Build\BatchFiles\RunUAT.bat")) { Write-Error "RunUAT missing"; exit 1 }
          if (!(Test-Path "$UEPath\Engine\Binaries\Win64\UnrealEditor.exe")) { Write-Error "UnrealEditor.exe missing"; exit 1 }
          if (!(Test-Path "$UEPath\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe")) { Write-Error "UBT missing"; exit 1 }

      - name: Clean previous outputs
        shell: powershell
        run: |
          @("Binaries","Intermediate","Saved/StagedBuilds","Saved/Cooked","Saved/Automation","Saved/Logs") |
            % { if (Test-Path $_) { Remove-Item -Recurse -Force $_ } }

      - name: Run BuildGraph CI Pipeline
        shell: powershell
        run: |
          $UEPath     = $env:UE_ENGINE_PATH
          $RunUATPath = Join-Path $UEPath 'Engine\Build\BatchFiles\RunUAT.bat'
          $RepoRoot   = $PWD.Path

          if (-not $env:PROJECT_ROOT -or -not (Test-Path $env:PROJECT_ROOT)) {
            $uproject = Get-ChildItem -Path $RepoRoot -Filter *.uproject -File -Recurse | Select-Object -First 1
            if (!$uproject) { Write-Error "No .uproject found"; exit 1 }
            $UProjectPath = $uproject.FullName
            $ProjectRoot  = Split-Path -Parent $UProjectPath
          } else {
            $ProjectRoot  = $env:PROJECT_ROOT
            $uproject = Get-ChildItem -Path $ProjectRoot -Filter *.uproject -File | Select-Object -First 1
            if (!$uproject) { Write-Error "No .uproject in PROJECT_ROOT"; exit 1 }
            $UProjectPath = $uproject.FullName
          }

          $ProjectName  = [IO.Path]::GetFileNameWithoutExtension($UProjectPath)
          $InputBuild   = "${{ github.event.inputs.build_script_path }}"
          $BuildScript  = if ([string]::IsNullOrWhiteSpace($InputBuild)) { Join-Path $ProjectRoot 'BuildScripts\Build.xml' } else { (Resolve-Path (Join-Path $RepoRoot $InputBuild)).Path }
          if (!(Test-Path $BuildScript)) { Write-Error "Build.xml not found: $BuildScript"; exit 1 }

          $EnableTests    = "${{ github.event.inputs.enable_tests || 'true' }}"
          $EnablePackage  = "${{ github.event.inputs.enable_packaging || 'true' }}"
          $BuildConfig    = $env:BUILD_CONFIGURATION
          $TargetPlatform = $env:TARGET_PLATFORM

          & $RunUATPath BuildGraph `
            -Script="$BuildScript" `
            -Target=CI `
            -set:ProjectName=$ProjectName `
            -set:ProjectRoot="$ProjectRoot" `
            -set:BuildConfiguration=$BuildConfig `
            -set:TargetPlatform=$TargetPlatform `
            -set:EnableTests=$EnableTests `
            -set:EnablePackage=$EnablePackage `
            -set:EnableLinting=true
          if ($LASTEXITCODE -ne 0) {
            if (Test-Path "Saved\Logs") { Get-ChildItem "Saved\Logs" -Filter "*.log" | Sort LastWriteTime -Desc | Select -First 1 | % { Get-Content $_.FullName -Tail 200 } }
            exit $LASTEXITCODE
          }

      - name: Collect CI bundle
        if: always()
        shell: powershell
        run: |
          $bundle = "ArtifactsBundle"
          if (Test-Path $bundle) { Remove-Item -Recurse -Force $bundle }
          New-Item -ItemType Directory -Path $bundle | Out-Null
          if (Test-Path ".\Saved\Automation\_Bundle") { robocopy ".\Saved\Automation\_Bundle" "$bundle" /E | Out-Null }
          @(
            @{From="Saved\Automation";   To="$bundle\_Raw\Automation"},
            @{From="Saved\Logs";         To="$bundle\_Raw\Logs"},
            @{From="Saved\StagedBuilds"; To="$bundle\_Raw\StagedBuilds"}
          ) | % {
            if (Test-Path $_.From) {
              New-Item -ItemType Directory -Path $_.To -Force | Out-Null
              robocopy $_.From $_.To /E | Out-Null
            }
          }
          Compress-Archive -Path "$bundle\*" -DestinationPath "ci-bundle.zip" -Force

      - name: Upload CI bundle (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-bundle-${{ env.BUILD_CONFIGURATION }}-${{ env.TARGET_PLATFORM }}
          path: ArtifactsBundle/**/*
          retention-days: 14

      - name: Upload CI bundle (zip)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-bundle-zip-${{ env.BUILD_CONFIGURATION }}-${{ env.TARGET_PLATFORM }}
          path: ci-bundle.zip
          retention-days: 30

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ env.BUILD_CONFIGURATION }}-${{ env.TARGET_PLATFORM }}
          path: Saved/Logs/**/*
          retention-days: 7

      - name: Upload Test Results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ env.BUILD_CONFIGURATION }}-${{ env.TARGET_PLATFORM }}
          path: Saved/Automation/**/*
          retention-days: 14

      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unreal Automation Tests
          path: |
            Saved/Automation/**/*.xml
            ArtifactsBundle/**/*.xml
          reporter: java-junit
          fail-on-error: false

      - name: Summary
        if: always()
        shell: powershell
        run: |
          $s = $env:GITHUB_STEP_SUMMARY
          "### Tests" | Out-File $s -Encoding utf8
          $n = (Get-ChildItem -Path "Saved\Automation","ArtifactsBundle" -Recurse -Filter *.xml -ErrorAction SilentlyContinue | Measure-Object).Count
          "JUnit files: $n" | Out-File $s -Append
          "### Performance (latest)" | Out-File $s -Append
          $auto = Join-Path $PWD 'PerformanceTestResults_Automation.csv'
          if (Test-Path $auto) {
            $rows = Import-Csv $auto
            if ($rows) {
              $h = ($rows[0].PSObject.Properties.Name)
              "| " + ($h -join " | ") + " |" | Out-File $s -Append
              "| " + (($h | % { "---" }) -join " | ") + " |" | Out-File $s -Append
              $rows | Select-Object -First 5 | % { "| " + ($h | % { "$($_.$_)" } -join " | ") + " |" } | Out-File $s -Append
            }
          } else {
            "No PerformanceTestResults_Automation.csv" | Out-File $s -Append
          }
          $arch = Join-Path $PWD 'ArchiveDirectory'
          if (Test-Path $arch) {
            $latest = Get-ChildItem $arch -Filter 'PerformanceTestResults_*.csv' | Sort LastWriteTime -Desc | Select -First 1
            if ($latest) {
              "`n$($latest.Name)" | Out-File $s -Append
              $rows = Import-Csv $latest.FullName
              if ($rows) {
                $h = ($rows[0].PSObject.Properties.Name)
                "| " + ($h -join " | ") + " |" | Out-File $s -Append
                "| " + (($h | % { "---" }) -join " | ") + " |" | Out-File $s -Append
                $rows | Select-Object -First 5 | % { "| " + ($h | % { "$($_.$_)" } -join " | ") + " |" } | Out-File $s -Append
              }
            }
          }

      - name: Create Release
        if: success() && github.ref == 'refs/heads/main' && (github.event.inputs.enable_packaging == 'true' || github.event.inputs.enable_packaging == null)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.run_number }}
          release_name: Build ${{ github.run_number }}
          body: |
            Build from ${{ github.sha }}
            Configuration: ${{ env.BUILD_CONFIGURATION }}
            Platform: ${{ env.TARGET_PLATFORM }}
          draft: false
          prerelease: ${{ env.BUILD_CONFIGURATION != 'Shipping' }}

      - name: Attach CI bundle to Release
        if: success() && github.ref == 'refs/heads/main' && (github.event.inputs.enable_packaging == 'true' || github.event.inputs.enable_packaging == null)
        uses: softprops/action-gh-release@v2
        with:
          files: ci-bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  static-analysis:
    name: Static Code Analysis
    runs-on: [self-hosted, windows]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Verify Precompiled Engine
        shell: powershell
        run: |
          $UEPath = $env:UE_ENGINE_PATH
          if (!(Test-Path "$UEPath\Engine\Build\BatchFiles\RunUAT.bat")) { Write-Error "RunUAT missing"; exit 1 }
      - name: BuildGraph Analyze
        shell: powershell
        run: |
          $UEPath = $env:UE_ENGINE_PATH
          $RunUATPath = "$UEPath\Engine\Build\BatchFiles\RunUAT.bat"
          $ProjectRoot = $PWD.Path
          & $RunUATPath BuildGraph `
            -Script="$ProjectRoot\BuildScripts\Build.xml" `
            -Target=Analyze `
            -set:ProjectName=$env:PROJECT_NAME `
            -set:ProjectRoot="$ProjectRoot" `
            -set:BuildConfiguration=$env:BUILD_CONFIGURATION `
            -set:EnableLinting=true
      - name: Upload Analysis Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-results
          path: Saved/Logs/**/*StaticAnalysis*
          retention-days: 7
